name: Pull request workflow

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[release]')"
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: rm -rf .npmrc
      - run: npm install -g yarn
      - run: yarn install
      - run: |
          echo @irevdev:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
      - run: yarn build:all
      - run: npm publish --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_BASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BASE_TOKEN }}
